### ISSUE TITLE
Spot price update

### ISSUE THREAD

**Issue by Bronimo25** [happycoder-se/HappySpotPrice#10]
Hi i have a flow where I look for changed on the spot price.

It seems that is does not currently get updates each hour. Don't know if issue only is for me. Today it was updated at 07.00 and again 09.00, so it skipped at 08.00

**Comment by happycoder-se** [comment]
Are you sure that the price at 8 was not the same as at 7?
Price change is triggered only if the price is changed.

**Comment by Bronimo25** [comment]
I believe so, according to my Price app it should be 0,00 at 08.00 and was 0,11 at 07.00

**Comment by happycoder-se** [comment]
> I believe so, according to my Price app it should be 0,00 at 08.00 and was 0,11 at 07.00

Ok! 

Can you go into the app and choose to send diagnostics log?

**Comment by Bronimo25** [comment]
db61df5d-fb4a-49ef-9d22-99d68ecb3ea5

**Comment by happycoder-se** [comment]
The app did a price check at 8:00, with no change detected. I can't see the price in the logs, 
I will add some more logging in next version, so debugging will show the price. 
There's also some strange happening while fetching the data. 

Thanks for the log, with will help me tweak the app even more.

**Comment by happycoder-se** [comment]
Added some more logging to address this issue. Please update to version 1.6.1.
Create a new issue when/if this problem occur again.
