### ISSUE TITLE
Spot Price not updating “token is null”

### ISSUE THREAD

**Issue by Bronimo25** [happycoder-se/HappySpotPrice#12]
Testing flow with get current Price, but it fail and say “token is null” 
Error log:
0ba8b16f-b0c9-4afa-ac0d-77e9c16fe159

**Comment by happycoder-se** [comment]
Sadly Nordpool has closed down API access. This app is now broken :(

**Comment by Bronimo25** [comment]
Will you correct API in app for fix? Or should I look for other options :)

**Comment by happycoder-se** [comment]
It would require too much effort from my side to adapt to their changes. 
Never say never, but you should start looking for an alternative :(

**Comment by Bronimo25** [comment]
All right all ready for a solution from a http request getting currentt Price👌🏻

**Comment by happycoder-se** [comment]
I might have found something useful... I'll get back in a day or so..

**Comment by happycoder-se** [comment]
Good news!
I found a way to get hourly prices. The daily average is not working, but on its way.
