### ISSUE TITLE
Nordpool

### ISSUE THREAD

**Issue by Solifer** [happycoder-se/HappySpotPrice#13]
Hi
Can this do the trick https://www.hvakosterstrommen.no/strompris-api

Regards
Henning Andersen

**Comment by happycoder-se** [comment]
Thanks, but that site only contain prices for Norway.
Good new though, I found a way to get hourly prices. The daily average is not working, but on its way.

**Comment by happycoder-se** [comment]
Fixed in version 2.0.x
