### ISSUE TITLE
spot price is one of the X highest hours of the day does not work

### ISSUE THREAD

**Issue by Uhedamej** [happycoder-se/HappySpotPrice#14]
Using inverted flow card

“spot price is one of the X lowest hours of the day”

translates into 

“spot price is one of the X highest hours of the day” 

but it does not act like that

It executes the flow if X is set to <24-the rank of highest price.

**Comment by happycoder-se** [comment]
You are probably right.... If I recall the logic is just reversed just as you described... I'll look into it..

**Comment by happycoder-se** [comment]
So, apparently the code cannot adapt to the "inverse" switch state. Homey just takes the returned value and invert it.
So the fix for this is plain textual. Instead of "price is one of the x lowest/highest" the text will be "price is/isn't one of the ...", fixed in version 2.0.7.
