### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by SWarnberg** [happycoder-se/HappySpotPrice#3]
Hi

This app is a good start. However, to make it really useful, with respect to today's varying prices, another condition card would be great. Something like:

`Spot prices is lower than {x} percentile`

Then I can really control things when the spot price is at the daily lowest, irrespective of the price. For instance, the pool pump needs to be running at the cheapest 12 hrs every day.

**Comment by happycoder-se** [comment]
Good suggestion, thx.
I will for sure add something like that.

**Comment by happycoder-se** [comment]
In the latest version of the app (1.6.0) there is a conditional card to check if `Spot price is one of the [x] lowest hours of the day`, hope that it fit your needs.
