### ISSUE TITLE
Possible Homey Early compatibility issue?

### ISSUE THREAD

**Issue by TKGHill** [happycoder-se/HappySpotPrice#4]
HI Johan,

just installed Happy Spot Price last night on my new Homey Early 2023.

Tried creating a super simple flow just for fun:

Any idea as to why the "targetPrice is not defined" message appears when using the test facility?
![HappySpot](https://github.com/happycoder-se/HappySpotPrice/assets/138122196/741206b4-0f14-4ad4-90fc-bf0ef31281b6)

**Comment by happycoder-se** [comment]
Hej,

Ser på skärmdumpen att du är svensk ☺️

Jag har inte sett det felmeddelandet tidigare. Men det är alltså bara när
du kör test på flödet?

Om du vill får du gärna göra en logg dump, ”More > Apps > Happy Spot Prive
> Gear icon > Create diagnostics report” så underlättar det felsökningen
för min del.


Vänliga hälsningar
Fredrik

tors 29 juni 2023 kl. 14:01 skrev TKGHill ***@***.***>:

**Comment by TKGHill** [comment]
Ja du har rätt såg att du är svensk också, men tänkte om ngn vill läsa att det var bättre att skriva på engelska:-).
Själklart, här kommer en logg dump: e6459dc5-0068-4e13-bc01-73af6ae98b29
Har precis fått min early 2023 så ja har bara börjat leka med den. Har solceller och timpris så det finns en ambition att börja leka med att flytta konsumtion baserat på spotpriset, därav mitt intresse för din app!!!
Tack för supporten!! /Tommy

**Comment by happycoder-se** [comment]
Klokt tänkt ☺️

Tack för loggen, ska kika på det vid tillfälle. Har semester nu så har lite
ledigt från datorn 😉

Vänliga hälsningar
Fredrik

fre 30 juni 2023 kl. 08:34 skrev TKGHill ***@***.***>:

**Comment by TKGHill** [comment]
Ingen panik alls Fredrik, har bara börjat leka och utforska ännu. Fick min 2023 i måndags så man är novis på det här än så länge. 
Tyckte det var en bra ide med spot bevakning, var ngt jag tänkt på ett tag som var ett av skälen att jag uppgraderade till Homey.
Ha en riktigt bra semester nu!!!

**Comment by happycoder-se** [comment]
Bug is fixed in version 1.2.0
