### ISSUE TITLE
Average spot price 1/2/4 weeks

### ISSUE THREAD

**Issue by SveinungTor** [happycoder-se/HappySpotPrice#6]
Hi Frederik! 

I was wondering how I can adjust my power usage in periods where the spot price is below the average spot price on Nordpool for the last 7, 14 or 30 days. Does your app have such a feature/threshold value? 

Best regards, Sveinung Torvik 

PS: Keep up the good work😉

**Comment by happycoder-se** [comment]
Hi Sveinung,
The app does not have any persistant storage, and cannot get the 7/14/30 days average.
I'm not sure if you can get the average from Homey Insights, if so all you need to do is write to the insigts log on price change.

**Comment by SveinungTor** [comment]
Hi,

and thanks for your reply.

I have not found any ways to activate such feature using the "Insight"
function in Homey Pro.

What kind of storage (NAS, SAN, S3/object) is needed for your app to
provide such a feature? I work within the IT sector and have such
infrastructure available, though the Hyperscalers (GCP, AWS, Azure) might
be a better option.. For my part I am willing to enter into a subscription
model if your App can contribute to smart energy usage and reduction in
overall costs.

Br,
Sveinung

**Comment by happycoder-se** [comment]
HI Sveinung,

Thanks for offering storage solutions for this app.
Currently data is fetched directly from NordPool, not via any service hosted for this app in particular.
Adding such feature that you are requesting will take a lot of time, time that I unfortunately do not have at the moment.

I will for sure keep this idéa in mind.

But... I just pushed a new version of the app. Inspired by your request I added a conditional card for over/below daily average price. Hope you find that useful.

Take care
/Fredrik

**Comment by SveinungTor** [comment]
Thank you Fredrik for your response. I believe that the feature I am
questioning about can provide a "per month" fee from the users of your app.
So, if you find enough time to implement this I would gladly support you in
the effort.

Should/could I push this feature request to Nordpool? I have had a business
relationship with them in the past actually, concerning their
infrastructure.

Br, Sveinung

**Comment by happycoder-se** [comment]
Hi again,

Turns out I can access historic daily average price for last month after all :)
Give me a few days or maybe a week, and I might have a "conditional card" for is in the app.

Regarding monthly subscription, I don't know if that's even possible via Homey store. Better keep things free for now :)

**Comment by happycoder-se** [comment]
Added conditional card to compare current price against last 1-31 days average.
Released in app version 1.4.0

**Comment by SveinungTor** [comment]
Thanks a lot Fredrik! :-) I have put out a post on the board
"Hjemmeautomasjon" on Facebook informing them about the new feature
:-) And again - thank you! Br, Sveinung

**Comment by SveinungTor** [comment]
Hi again Fredrik,

and happy new year!

[image: image.png]

Homey reports a fault when trying to use the new functionality in your
Happy Spot Price app/card, any idea if the average price function is
working correctly?

Best regards,
Sveinung Torvik
Happy Spot Price user :-)

**Comment by happycoder-se** [comment]
Hi SveinungTor.
I can't see the attached image. Can you please contact me via email instead? info@happycoder.se

Thanks 
Fredrik
