### ISSUE TITLE
Appen slutar att fungera på kvällen

### ISSUE THREAD

**Issue by Svante23** [happycoder-se/HappySpotPrice#8]
Använder appen för att köra ett flow i Homey Pro 2023, när elpriset ändras dvs varje timme. Det fungerar bra fram till klockan 21 eller 23 sedan sker inget. För att få igång mitt flow igen måste jag gå in i inställningar och starta om appen. Då fungerar det under dagen fram till kvällen igen. Sedan måste jag göra ny omstart igen. Då missar jag alla prisändringarna fram till omstarten.

**Comment by happycoder-se** [comment]
Det låter märkligt. Kan du gå in under appens inställningar och välja att
skicka diagnostikrapport. Gärna efter att appen slutat uppdatera.

Vänliga hälsningar
Fredrik

sön 3 mars 2024 kl. 08:31 skrev Svante23 ***@***.***>:

**Comment by Svante23** [comment]
Tack för snabbt svar.
Jag kan gå in och skicka en nu och sedan en till när den inte funkar.

Med vänlig hälsning
Lennart Svantesson
tel mobil 070-xxxxxxxx


sön 3 mars 2024 kl. 09:57 skrev happy coder ***@***.***>:

**Comment by happycoder-se** [comment]
Det vore toppen, underlättar min felsökning

Tack

sön 3 mars 2024 kl. 10:49 skrev Svante23 ***@***.***>:

**Comment by Svante23** [comment]
ee1d9fea-0c51-48f5-b1d3-e9fb02b3898c


Med vänlig hälsning
Lennart Svantesson
tel mobil 070-6954810


sön 3 mars 2024 kl. 10:51 skrev happy coder ***@***.***>:

**Comment by Svante23** [comment]
e5a18d9e-b76e-4a55-b6d9-0a6f3905bd64
Nu uppdateras den inte Carle timme

Med vänlig hälsning
Lennart Svantesson


sön 3 mars 2024 kl. 10:52 skrev Lennart Svantesson <
***@***.***>:

**Comment by happycoder-se** [comment]
Hittar tyvärr ingenting uppenbart. Jag har uppdaterat alla externa beroenden och lagt till lite mer loggning i hopp om att det skall lösas eller vägleda lite till vad som går fel. Det verkar som att Nordpool slutar svara, vilket är märkligt då det fungerar fint för andra.

Se gärna till att uppdatera HappySpotPrice till 1.5.0 och så skickar du nya dumpar imorgon. Jag får då automatiskt mail så du behöver inte kopiera och maila logg id/guid.

**Comment by happycoder-se** [comment]
Fixed in v 1.5.1

**Comment by Svante23** [comment]
Hej igen!

Jag har nu använt din app sedan vi hade kontakt i våras och allt har funkat
bra!
Efter den senaste uppdateringen för 3 dagar sedan fungerar inte mina flow,
där jag har och-kortet med lägst pris under ett antal timmar. När jag
testar stannar det vid det kortet!

Hälsningar
Lennart


ons 20 mars 2024 kl. 11:24 skrev happy coder ***@***.***>:

**Comment by happycoder-se** [comment]
Hej

För 3-4 dagar sedan stängde Nordpool ner sitt öppna API, appen är då
oanvändbar.

Releasen jag gjorde var bara för att skriva det i ”release notes”.

Jag har ansökt om tillgång till Nordpools data, återstår att se ifall jag
får det samt hur man tillåts använda datat.

Oavsett så lär det tyvärr dröja innan jag i så fall skrivit om appen till
att passa deras nya system.



sön 13 okt. 2024 kl. 19:04 skrev Svante23 ***@***.***>:

**Comment by Svante23** [comment]
Det var ju synd när det funkade så bra. Jag hoppas att det löser sig. Lycka
till!

Hälsningar
Lennart


sön 13 okt. 2024 kl. 23:06 skrev happy coder ***@***.***>:

**Comment by happycoder-se** [comment]
Ja verkligen synd.
Jag har nu kikat lite närmare och det ställs helt andra krav än tidigare på
att nyttja Nordpool API.
Som jag tolkar det kommer jag behöva utveckla och drifta en service för att
inte anropa Nordpool för ofta. Dessutom tillsammans med Nordpool genomgå
accepstanstester innan driftsättning av denna service.
Det blir tyvärr för stor arbetsinsats för något som jag skapat på fritiden
:(

Den mån 14 okt. 2024 kl 08:44 skrev Svante23 ***@***.***>:
