### ISSUE TITLE
Laveste pris

### ISSUE THREAD

**Issue by Eikland** [happycoder-se/HappySpotPrice#9]
Dersom laveste pris er under 0, virker det som om -0,85 er lavere enn -1,35.
Bruker du ABS på på verdiene?

**Comment by Eikland** [comment]
Jeg har flow med 2 laveste pris timer.
Idag ble flow aktivert ved 3 laveste pris.

**Comment by happycoder-se** [comment]
Thanks for reporting these issues. I'll look into it.

**Comment by happycoder-se** [comment]
Fixed in version 1.6.1
